[package]
name = "byokey-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace    = true
description.workspace = true
license.workspace    = true
repository.workspace = true
homepage.workspace   = true

[lints]
workspace = true

[dependencies]
byokey-types = { workspace = true, features = ["reqwest"] }
byokey-auth.workspace = true
aigw-core.workspace = true
reqwest.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
bon.workspace = true
futures-util.workspace = true
bytes.workspace = true
tracing.workspace = true
sha2.workspace = true
hex = "0.4"
uuid = { version = "1", features = ["v4", "v5"] }
http.workspace = true
flate2 = "1.1.10"
tokio-stream.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
byokey-store.workspace = true
